# Generated by Django 5.2.4 on 2025-07-20 19:06

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "current_wpm",
                    models.PositiveIntegerField(
                        default=250,
                        help_text="User's current words-per-minute reading speed.",
                    ),
                ),
                (
                    "max_wpm",
                    models.PositiveIntegerField(
                        default=250,
                        help_text="User's highest achieved words-per-minute.",
                    ),
                ),
                (
                    "total_xp",
                    models.PositiveIntegerField(
                        default=0, help_text="Total accumulated experience points (XP)."
                    ),
                ),
                (
                    "current_xp_points",
                    models.PositiveIntegerField(
                        default=0, help_text="Spendable experience points."
                    ),
                ),
                (
                    "negative_xp_points",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Accumulated negative XP for admin tracking.",
                    ),
                ),
                (
                    "last_successful_wpm_used",
                    models.PositiveIntegerField(
                        default=250,
                        help_text="The WPM setting used on the last successfully completed quiz.",
                    ),
                ),
                (
                    "ad_free_articles_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of ad-free articles the user can access.",
                    ),
                ),
                (
                    "has_font_opensans",
                    models.BooleanField(
                        default=False,
                        help_text="User has purchased OpenSans font option.",
                    ),
                ),
                (
                    "has_font_opendyslexic",
                    models.BooleanField(
                        default=False,
                        help_text="User has purchased OpenDyslexic font for dyslexia-friendly reading.",
                    ),
                ),
                (
                    "has_font_roboto",
                    models.BooleanField(
                        default=False,
                        help_text="User has purchased Roboto font option.",
                    ),
                ),
                (
                    "has_font_merriweather",
                    models.BooleanField(
                        default=False,
                        help_text="User has purchased Merriweather font option.",
                    ),
                ),
                (
                    "has_font_playfair",
                    models.BooleanField(
                        default=False,
                        help_text="User has purchased Playfair Display font option.",
                    ),
                ),
                (
                    "has_2word_chunking",
                    models.BooleanField(
                        default=False,
                        help_text="User has purchased 2-word chunking capability.",
                    ),
                ),
                (
                    "has_3word_chunking",
                    models.BooleanField(
                        default=False,
                        help_text="User has purchased 3-word chunking capability.",
                    ),
                ),
                (
                    "has_4word_chunking",
                    models.BooleanField(
                        default=False,
                        help_text="User has purchased 4-word chunking capability.",
                    ),
                ),
                (
                    "has_5word_chunking",
                    models.BooleanField(
                        default=False,
                        help_text="User has purchased 5-word chunking capability.",
                    ),
                ),
                (
                    "has_smart_connector_grouping",
                    models.BooleanField(
                        default=False,
                        help_text="User has purchased smart connector grouping (groups stop words like 'the dragon').",
                    ),
                ),
                (
                    "has_smart_symbol_handling",
                    models.BooleanField(
                        default=False,
                        help_text="User has purchased smart symbol handling (elegant punctuation display).",
                    ),
                ),
                (
                    "last_xp_earned",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp of when user last earned XP.",
                        null=True,
                    ),
                ),
                (
                    "xp_earning_streak",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Current streak of consecutive days earning XP.",
                    ),
                ),
                (
                    "lifetime_xp_earned",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Total XP earned throughout user's lifetime.",
                    ),
                ),
                (
                    "lifetime_xp_spent",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Total XP spent throughout user's lifetime.",
                    ),
                ),
                (
                    "perfect_quiz_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of perfect (100%) quiz scores achieved.",
                    ),
                ),
                (
                    "quiz_attempts_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Total number of quiz attempts made."
                    ),
                ),
                (
                    "preferred_language",
                    models.CharField(
                        default="en",
                        help_text="User's preferred language for the UI and content (e.g., 'en', 'es').",
                        max_length=10,
                    ),
                ),
                (
                    "theme",
                    models.CharField(
                        default="light",
                        help_text="User's preferred visual theme (e.g., 'light', 'dark').",
                        max_length=20,
                    ),
                ),
                (
                    "llm_api_key_encrypted",
                    models.CharField(
                        blank=True,
                        help_text="User's encrypted API key for a preferred LLM provider.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "preferred_llm_model",
                    models.CharField(
                        blank=True,
                        help_text="The specific LLM model the user prefers to use.",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="AdminCorrectionDataset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "original_article_url",
                    models.URLField(
                        blank=True,
                        help_text="The URL of the original article.",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "original_content_hash",
                    models.CharField(
                        blank=True,
                        help_text="SHA-256 hash of the original content to ensure integrity.",
                        max_length=64,
                        null=True,
                    ),
                ),
                (
                    "corrected_content",
                    models.TextField(
                        blank=True,
                        help_text="The corrected version of the text content.",
                        null=True,
                    ),
                ),
                (
                    "correction_type",
                    models.CharField(
                        blank=True,
                        help_text="Type of correction (e.g., 'summary', 'quiz', 'content').",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "admin_user",
                    models.ForeignKey(
                        blank=True,
                        help_text="The admin user who made the correction.",
                        limit_choices_to={"is_staff": True},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(max_length=500, null=True, unique=True)),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                (
                    "image_url",
                    models.URLField(
                        blank=True,
                        help_text="URL of the article's main image.",
                        max_length=500,
                        null=True,
                    ),
                ),
                ("language", models.CharField(default="en", max_length=10)),
                (
                    "processing_status",
                    models.CharField(default="pending", max_length=20),
                ),
                ("quiz_data", models.JSONField(blank=True, null=True)),
                (
                    "raw_content",
                    models.TextField(
                        blank=True,
                        help_text="Original raw content of the article before processing.",
                        null=True,
                    ),
                ),
                ("source", models.CharField(default="user_submission", max_length=100)),
                ("publication_date", models.DateTimeField(blank=True, null=True)),
                (
                    "article_type",
                    models.CharField(
                        choices=[
                            ("regular", "Regular Article"),
                            ("wikipedia", "Wikipedia Article"),
                        ],
                        default="regular",
                        help_text="Type of article: regular user submission or Wikipedia article",
                        max_length=20,
                    ),
                ),
                ("word_count", models.PositiveIntegerField(blank=True, null=True)),
                ("letter_count", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "summary",
                    models.TextField(
                        blank=True, help_text="Article summary or excerpt", null=True
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "llm_model_used",
                    models.CharField(
                        blank=True,
                        help_text="The LLM model used for processing this article.",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("reading_level", models.FloatField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="verifast_app.article",
                    ),
                ),
                (
                    "parent_comment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="verifast_app.comment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QuizAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.FloatField()),
                ("wpm_used", models.IntegerField()),
                ("xp_awarded", models.IntegerField()),
                (
                    "result",
                    models.JSONField(
                        blank=True,
                        help_text="Detailed results of the quiz attempt.",
                        null=True,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "reading_time_seconds",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Time spent reading the article in seconds.",
                        null=True,
                    ),
                ),
                (
                    "quiz_time_seconds",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Time spent taking the quiz in seconds.",
                        null=True,
                    ),
                ),
                (
                    "quiz_rating",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="User's rating of the quiz (e.g., 1-5 stars).",
                        null=True,
                    ),
                ),
                (
                    "quiz_feedback",
                    models.TextField(
                        blank=True, help_text="User's feedback on the quiz.", null=True
                    ),
                ),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="verifast_app.article",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("wikipedia_url", models.URLField(blank=True, null=True)),
                ("wikipedia_content", models.TextField(blank=True, null=True)),
                ("is_validated", models.BooleanField(default=False)),
                ("article_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["name"], name="verifast_ap_name_210cfa_idx"),
                    models.Index(
                        fields=["is_validated"], name="verifast_ap_is_vali_7e233e_idx"
                    ),
                    models.Index(
                        fields=["-article_count"], name="verifast_ap_article_921cfa_idx"
                    ),
                ],
            },
        ),
        migrations.AddField(
            model_name="article",
            name="tags",
            field=models.ManyToManyField(blank=True, to="verifast_app.tag"),
        ),
        migrations.CreateModel(
            name="XPTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("EARN", "Earned"), ("SPEND", "Spent")],
                        help_text="Whether this transaction earned or spent XP.",
                        max_length=5,
                    ),
                ),
                (
                    "amount",
                    models.IntegerField(
                        help_text="XP amount (positive for earn, negative for spend)."
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("quiz_completion", "Quiz Completion"),
                            ("perfect_score_bonus", "Perfect Score Bonus"),
                            ("wpm_improvement", "WPM Improvement"),
                            ("reading_streak", "Reading Streak"),
                            ("comment_post", "Comment Posted"),
                            ("comment_reply", "Comment Reply"),
                            ("interaction_bronze", "Bronze Interaction"),
                            ("interaction_silver", "Silver Interaction"),
                            ("interaction_gold", "Gold Interaction"),
                            ("interaction_reward", "Interaction Reward"),
                            ("feature_purchase", "Feature Purchase"),
                            ("admin_adjustment", "Admin Adjustment"),
                        ],
                        help_text="The source/reason for this XP transaction.",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Detailed description of the transaction."
                    ),
                ),
                (
                    "balance_after",
                    models.PositiveIntegerField(
                        help_text="User's spendable XP balance after this transaction."
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this transaction occurred."
                    ),
                ),
                (
                    "feature_purchased",
                    models.CharField(
                        blank=True,
                        help_text="Name of feature purchased (if applicable).",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "comment",
                    models.ForeignKey(
                        blank=True,
                        help_text="Comment that triggered this transaction (if applicable).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="verifast_app.comment",
                    ),
                ),
                (
                    "quiz_attempt",
                    models.ForeignKey(
                        blank=True,
                        help_text="Quiz attempt that triggered this transaction (if applicable).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="verifast_app.quizattempt",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user involved in this XP transaction.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="xp_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "XP Transaction",
                "verbose_name_plural": "XP Transactions",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="FeaturePurchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "feature_name",
                    models.CharField(
                        help_text="Internal name of the purchased feature.",
                        max_length=50,
                    ),
                ),
                (
                    "feature_display_name",
                    models.CharField(
                        help_text="Human-readable name of the purchased feature.",
                        max_length=100,
                    ),
                ),
                (
                    "xp_cost",
                    models.PositiveIntegerField(
                        help_text="XP cost of the feature at time of purchase."
                    ),
                ),
                (
                    "purchase_date",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the feature was purchased."
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user who purchased the feature.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feature_purchases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        help_text="The XP transaction record for this purchase.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="verifast_app.xptransaction",
                    ),
                ),
            ],
            options={
                "verbose_name": "Feature Purchase",
                "verbose_name_plural": "Feature Purchases",
                "ordering": ["-purchase_date"],
            },
        ),
        migrations.CreateModel(
            name="CommentInteraction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "interaction_type",
                    models.CharField(
                        choices=[
                            ("BRONZE", "Bronze"),
                            ("SILVER", "Silver"),
                            ("GOLD", "Gold"),
                            ("REPORT_TROLL", "Report: Troll"),
                            ("REPORT_BAD", "Report: Bad"),
                            ("REPORT_SHIT", "Report: Shit"),
                        ],
                        help_text="Type of interaction (e.g., Bronze, Silver, Gold, Report Tiers).",
                        max_length=15,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "xp_cost",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="XP cost incurred by the user for this interaction.",
                    ),
                ),
                (
                    "comment",
                    models.ForeignKey(
                        help_text="The comment being interacted with.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="verifast_app.comment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user who performed the interaction.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "comment")},
            },
        ),
        migrations.AddIndex(
            model_name="xptransaction",
            index=models.Index(
                fields=["user", "-timestamp"], name="verifast_ap_user_id_57c803_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="xptransaction",
            index=models.Index(
                fields=["transaction_type", "-timestamp"],
                name="verifast_ap_transac_a61bf1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="xptransaction",
            index=models.Index(
                fields=["source", "-timestamp"], name="verifast_ap_source_030539_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="featurepurchase",
            index=models.Index(
                fields=["user", "-purchase_date"], name="verifast_ap_user_id_dcc388_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="featurepurchase",
            index=models.Index(
                fields=["feature_name", "-purchase_date"],
                name="verifast_ap_feature_620b9e_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="featurepurchase",
            unique_together={("user", "feature_name")},
        ),
    ]
