# Generated by Django 5.2.4 on 2025-07-23 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("verifast_app", "0003_fix_tag_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="ad_free_articles_count",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Number of ad-free articles the user can access.",
                verbose_name="Ad-free Articles Count",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="current_wpm",
            field=models.PositiveIntegerField(
                default=250,
                help_text="User's current words-per-minute reading speed.",
                verbose_name="Current WPM",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="current_xp_points",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Spendable experience points.",
                verbose_name="Current XP Points",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="last_successful_wpm_used",
            field=models.PositiveIntegerField(
                default=250,
                help_text="The WPM setting used on the last successfully completed quiz.",
                verbose_name="Last Successful WPM Used",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="max_wpm",
            field=models.PositiveIntegerField(
                default=250,
                help_text="User's highest achieved words-per-minute.",
                verbose_name="Maximum WPM",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="negative_xp_points",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Accumulated negative XP for admin tracking.",
                verbose_name="Negative XP Points",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="total_xp",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Total accumulated experience points (XP).",
                verbose_name="Total XP",
            ),
        ),
    ]
