# Generated by Django 5.2.4 on 2025-07-30 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("verifast_app", "0006_auto_20250729_0222"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="article",
            name="verifast_app_article_acquisition_source_idx",
        ),
        migrations.RemoveIndex(
            model_name="article",
            name="verifast_app_article_topic_category_idx",
        ),
        migrations.RemoveIndex(
            model_name="article",
            name="verifast_app_article_acquisition_timestamp_idx",
        ),
        migrations.RenameIndex(
            model_name="contentacquisitionlog",
            new_name="verifast_ap_timesta_0f66c7_idx",
            old_name="verifast_app_contentacquisitionlog_timestamp_idx",
        ),
        migrations.RenameIndex(
            model_name="contentacquisitionlog",
            new_name="verifast_ap_acquisi_fb76e0_idx",
            old_name="verifast_app_contentacquisitionlog_acq_type_timestamp_idx",
        ),
        migrations.RenameIndex(
            model_name="contentacquisitionlog",
            new_name="verifast_ap_source__82b499_idx",
            old_name="verifast_app_contentacquisitionlog_source_timestamp_idx",
        ),
    ]
