"""Add is_user_submitted to Article

Revision ID: 0c4055ebbb3e
Revises: 68fdefd2f1fa
Create Date: 2025-06-24 14:34:53.482772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c4055ebbb3e'
down_revision = '68fdefd2f1fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_user_submitted', sa.Boolean(), server_default='false', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.drop_column('is_user_submitted')

    # ### end Alembic commands ###
