"""Añadir campo is_admin a User

Revision ID: 7e26bc5326e3
Revises: 5594946623e2
Create Date: 2025-06-25 16:43:28.580444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e26bc5326e3'
down_revision = '5594946623e2'
branch_labels = None
depends_on = None


def upgrade():
    # Paso 1: Añadir la columna 'is_admin' como nullable=True inicialmente
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))

    # Paso 2: Actualizar las filas existentes para establecer un valor por defecto (False)
    # Esto es crucial para SQLite antes de hacer la columna NOT NULL
    op.execute("UPDATE user SET is_admin = 0 WHERE is_admin IS NULL")

    # Paso 3: Alterar la columna para que sea NOT NULL y establecer un server_default
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('is_admin',
                              existing_type=sa.Boolean(),
                              nullable=False,
                              existing_nullable=True,
                              server_default=sa.false()) # Establece el valor por defecto para nuevas filas



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
