"""Add theme column to User model

Revision ID: 9a16c565a34c
Revises: f6eb5bfa34dd
Create Date: 2025-06-22 22:02:36.923823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a16c565a34c'
down_revision = 'f6eb5bfa34dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('theme', sa.String(length=10), server_default='auto', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('theme')

    # ### end Alembic commands ###
